name: Setup Python Playwright Environment
description: Install Python dependencies and Playwright browsers for testing.
inputs:
  python-version:
    description: Python version to install.
    required: false
    default: '3.11'
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Playwright browsers
      shell: bash
      run: |
        python -m playwright install --with-deps chromium
